#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np

RPS = input("Enter R, P or S to start playing:")
possible_input = ['R','P','S']

# Text that is printed when the game is over.

Win = "You win, congratulations!"
Lose = "You lost."

# Generates a random number between 0 and 3, then gets the value of that number from the list possible_input

indx = np.random.randint(0,len(possible_input))
result = possible_input[indx]

def RockPapSci(RPS, result):
    """ This function evaluates a random value against user input in Rock-paper-Scissors, then prints if you've won or lost.
        This function written by Klingens on 03-03-2026.

    Parameters
    ----------
    RPS (str) the user input of R, P or S
    result (str) the random vale R, P or S, generated by the programme
    
    Return
    -------
    count (int) the number of times you tried to win
    """
    game = True  # condition
    count = 1
    while game:
        print(f"The programme chose: {result}")
        if RPS != 'R' and 'P' and 'S':  # Evaluates whether the input is valid. If not, enter something again.
            print("Invalid input, try again")
            RPS = input("Enter R, P or S to try again:")
            result = possible_input[indx]
        elif RPS == 'R' and result == 'S':
            game = False  # Ends the game
            print(Win)
        elif RPS == 'P' and result == 'S':
            game = False
            print(Lose)
        elif RPS == 'R' and result == 'P':
            game = False
            print(Lose)
        elif RPS == 'P' and result == 'R':
            game = False
            print(Win)
        elif RPS == 'S' and result == 'P':
            game = False
            print(Win)
        elif RPS == 'S' and result == 'R':
            game = False
            print(Lose)
        else:
            print(f"It's a tie, try again.")
            RPS = input("Enter R, P or S to try again:")  # Asks user to enter a new number due to a draw.
            result = possible_input[indx]
            count += 1  # Ups the count of number of tries by 1
    return count

print(f"You tried {RockPapSci(RPS, result)} times.")


# In[ ]:




